other fixes

diff --git a/roles/agama_client/templates/agama-client.j2 b/roles/agama_client/templates/agama-client.j2
--- a/roles/agama_client/templates/agama-client.j2
+++ b/roles/agama_client/templates/agama-client.j2
@@ -1,4 +1,4 @@
-#!/bin/bash -e
+#!/bin/bash -eu
 
 # Please help Dora to find problems in this script
 
@@ -17,15 +17,17 @@ db_url=$(grep "^database_url=" /etc/agama-client/agama-client.conf | sed 's/^.*=
 db_name=$(grep "^database_name=" /etc/agama-client/agama-client.conf | sed 's/^.*=//')
 subnet=$(grep "^subnet=" /etc/agama-client/agama-client.conf | sed 's/^.*=//')
 
-if $(curl -s "$db_url/ping"); then
-    logger "Will push data to $db_url"
-else
-    logger "Failed to connect to $db_url"
-    exit 1
-fi
+for i in {1..30}; do
+    if $(curl -s "$db_url/ping"); then
+        logger "Will push data to $db_url"
+        break
+    else
+        logger "Failed to connect to $db_url. InfluxDB is not running? ($i)"
+        sleep 5
+    fi
+done
 
 logger "Creating database $db_name in $db_url"
-# curl -i -XPOST "$db_url/query" --data-urlencode "q=CREATE DATABASE $db_name" 1>/dev/null 2>/dev/null || { logger "$0 Failed to create database"; exit 1; }
 curl -i -XPOST "$db_url/query" --data-urlencode "q=CREATE DATABASE $db_name" 1>/dev/null 2>/dev/null || { logger "$0 Failed to create database"; exit 1; }
 
 while true; do
@@ -43,6 +45,11 @@ while true; do
         if [ -z $vm_name ]; then
             # No agama running, skipping
             continue
+        fi
+        ptr=$(host -W1 $vm_ip $vm_ip | awk '/domain name pointer/ {print $5}')
+        if ! [ -z "$ptr" ]; then
+            logger "Resolved $vm_ip to $ptr"
+            vm_name="$ptr"
         fi
         # Number of items in agama
         table_rows=$(echo "$content" | grep -c "</tr>")
